### PR TITLE
add oci image build

### PR DESCRIPTION
**Pull request by jhoblitt**

### CODE REVIEW

**Review by womullan — APPROVED** [review]
@ktlim if this is production should it move to lsst ?   I guess i thought we would run this on the nodes with puppet - camera team dont use containers and this will be on the camera diagnostic nodes
the build looks good to me though

**Comment by jhoblitt** [comment]
I am planning to deploy a systemd service unit via puppet that uses this OCI image.

**Comment by jhoblitt** [comment]
It seems there may be a complication with installing await code as a setuptools script.
```
Sep 06 17:34:19 jhoblitt-test2.dev.lsst.org systemd-s3daemon[696498]: <coroutine object main at 0x7faf99dd1f40>
Sep 06 17:34:19 jhoblitt-test2.dev.lsst.org systemd-s3daemon[696498]: sys:1: RuntimeWarning: coroutine 'main' was never awaited
Sep 06 17:34:19 jhoblitt-test2.dev.lsst.org systemd-s3daemon[696498]: RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by jhoblitt** [comment]
I think `asyncio.run` just needs to be called from the script entry function...

**Pull request merged**
